<a href="https://colab.research.google.com/github/adritoo23-prog/BIT2/blob/main/TP1/Taller_Adriana_Toro_Mahecha_20_May_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Taller — Limpieza y Análisis de Datos con Pandas y NumPy

Adriana Toro Mahecha
20/05/2026

Parte 1 — Exploración de datos (Pandas)

In [82]:
#se importan las librerias que se usaran para desarrollar el ejercicio

import pandas as pd
import numpy as np

In [83]:
#se carga el archivo al entorno de desarrollo para asi mismo poder leerlo dentro del código usando Pandas con la funcion leer CSV. Se define la variable
df= pd.read_csv('ventas_sucias_5000.csv')
df

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha
0,Maria,Monitor,1326.0,NaN,peru,Efectivo,2024-01-01 00:00:00
1,Luisa,Laptop,55.0,2,chile,Tarjeta,2024-01-01 01:00:00
2,Carlos,Monitor,1203.0,9,Colombia,Efectivo,2024-01-01 02:00:00
3,Luisa,Monitor,1304.0,3,Perú,TRANSFERENCIA,2024-01-01 03:00:00
4,Luisa,Monitor,426.0,6,chile,Tarjeta,2024-01-01 04:00:00
...,...,...,...,...,...,...,...
4995,Juan,Laptop,1582.0,8,chile,transferencia,2024-07-27 03:00:00
4996,Carlos,Mouse,1553.0,2,Perú,Tarjeta,2024-07-27 04:00:00
4997,Juan,Monitor,1776.0,2,chile,Efectivo,2024-07-27 05:00:00
4998,Pedro,Laptop,1366.0,8,Chile,TRANSFERENCIA,2024-07-27 06:00:00
4999,Pedro,Mouse,406.0,1,chile,TRANSFERENCIA,2024-07-27 00:00:00

In [84]:
#primeras filas

df.head()

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha
0,Maria,Monitor,1326.0,NaN,peru,Efectivo,2024-01-01 00:00:00
1,Luisa,Laptop,55.0,2,chile,Tarjeta,2024-01-01 01:00:00
2,Carlos,Monitor,1203.0,9,Colombia,Efectivo,2024-01-01 02:00:00
3,Luisa,Monitor,1304.0,3,Perú,TRANSFERENCIA,2024-01-01 03:00:00
4,Luisa,Monitor,426.0,6,chile,Tarjeta,2024-01-01 04:00:00

In [85]:
#se imprime información general del dataset ¿Qué tipos de datos identificas? textos y numeros ¿Encuentras columnas con problemas o inconsistencias? Si, algunas columnas no tienen los datos completos (precio, cantidad), cantidad deberiamos tener número y no texto

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cliente      5000 non-null   object
 1   producto     5000 non-null   object
 2   precio       4950 non-null   float64
 3   cantidad     4950 non-null   object
 4   pais         5000 non-null   object
 5   metodo_pago  5000 non-null   object
 6   fecha        5000 non-null   object
dtypes: float64(1), object(6)
memory usage: 273.6+ KB

In [86]:
#resumen estadistico

df.describe(include='all')

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha
count,5000,5000,4950.000000,4950,5000,5000,5000
unique,6,5,NaN,10,7,4,4825
top,Ana,Mouse,NaN,2,chile,TRANSFERENCIA,2024-01-19 00:00:00
freq,870,1069,NaN,573,733,1276,5
mean,NaN,NaN,5053.823434,NaN,NaN,NaN,NaN
std,NaN,NaN,63379.982009,NaN,NaN,NaN,NaN
min,NaN,NaN,10.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,531.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,1027.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,1519.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,999999.000000,NaN,NaN,NaN,NaN

In [87]:
#¿Cuántas filas y columnas tiene la base de datos?

df.shape

(5000, 7)

Parte 2 — Limpieza de datos (Pandas)

In [88]:
##No se evidencian registros duplicados.
df.duplicated().sum()

np.int64(0)

In [89]:
#Corregir tipos de datos incorrectos; sin embargo se genra una copia de DF para hacer la limpieza

dfcopy1= df.copy()

Se valida la información de cada columna, con el fin de evidenciar datos a corregir y unificar

In [90]:
dfcopy1["cliente"].unique()

#nada por corregir

array(['Maria', 'Luisa', 'Carlos', 'Juan', 'Pedro', 'Ana'], dtype=object)

In [91]:
dfcopy1["producto"].unique()

#nada por corregir

array(['Monitor', 'Laptop', 'Celular', 'Mouse', 'Teclado'], dtype=object)

In [92]:
dfcopy1["fecha"].unique()

#nada por corregir pero si cambiar a tipo de dato fecha

array(['2024-01-01 00:00:00', '2024-01-01 01:00:00',
       '2024-01-01 02:00:00', ..., '2024-07-27 04:00:00',
       '2024-07-27 05:00:00', '2024-07-27 06:00:00'], dtype=object)

In [93]:
#fecha

dfcopy1["fecha"]=pd.to_datetime(dfcopy1["fecha"])
dfcopy1["fecha"].unique()

<DatetimeArray>
['2024-01-01 00:00:00', '2024-01-01 01:00:00', '2024-01-01 02:00:00',
 '2024-01-01 03:00:00', '2024-01-01 04:00:00', '2024-01-01 05:00:00',
 '2024-01-01 06:00:00', '2024-01-01 07:00:00', '2024-01-01 08:00:00',
 '2024-01-01 09:00:00',
 ...
 '2024-07-26 21:00:00', '2024-07-26 22:00:00', '2024-07-26 23:00:00',
 '2024-07-27 00:00:00', '2024-07-27 01:00:00', '2024-07-27 02:00:00',
 '2024-07-27 03:00:00', '2024-07-27 04:00:00', '2024-07-27 05:00:00',
 '2024-07-27 06:00:00']
Length: 4825, dtype: datetime64[ns]

In [94]:
dfcopy1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cliente      5000 non-null   object
 1   producto     5000 non-null   object
 2   precio       4950 non-null   float64
 3   cantidad     4950 non-null   object
 4   pais         5000 non-null   object
 5   metodo_pago  5000 non-null   object
 6   fecha        5000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 273.6+ KB

In [95]:
dfcopy1["pais"].unique()

#se debe corregir y unificar datos en la columna

array(['peru', 'chile', 'Colombia', 'Perú', 'COL', 'Chile', 'col'],
      dtype=object)

In [96]:
#unificar Mayusculas con Title
dfcopy1["pais"]=dfcopy1["pais"].str.title()
dfcopy1["pais"].unique()

array(['Peru', 'Chile', 'Colombia', 'Perú', 'Col'], dtype=object)

In [97]:
#unificar pais
dfcopy1["pais"]=dfcopy1["pais"].replace({
    "Perú":"Peru",
    "Col":"Colombia"
})
dfcopy1["pais"].unique()

array(['Peru', 'Chile', 'Colombia'], dtype=object)

In [98]:
dfcopy1["cantidad"].unique()

#unificar a numero la información

array([nan, '2', '9', '3', '6', '7', '1', '8', '5', '4', 'three'],
      dtype=object)

In [99]:
#se corrige texto a número

dfcopy1["cantidad"]=dfcopy1["cantidad"].replace({
    "three":"3"
})
dfcopy1["cantidad"].unique()

array([nan, '2', '9', '3', '6', '7', '1', '8', '5', '4'], dtype=object)

In [100]:
#valores nulos identificados, convertir columna a número

dfcopy1["cantidad"]=pd.to_numeric(dfcopy1["cantidad"], errors="coerce")
dfcopy1["cantidad"].unique()

array([nan,  2.,  9.,  3.,  6.,  7.,  1.,  8.,  5.,  4.])

In [101]:
#nulos

dfcopy1["cantidad"]=dfcopy1["cantidad"].fillna(dfcopy1["cantidad"].median())
dfcopy1["cantidad"].unique()

array([5., 2., 9., 3., 6., 7., 1., 8., 4.])

In [102]:
dfcopy1["metodo_pago"].unique()

#unificar metodos de pago

array(['Efectivo', 'Tarjeta', 'TRANSFERENCIA', 'transferencia'],
      dtype=object)

In [103]:
dfcopy1["metodo_pago"]=dfcopy1["metodo_pago"].str.title()
dfcopy1["metodo_pago"].unique()

array(['Efectivo', 'Tarjeta', 'Transferencia'], dtype=object)

In [104]:
#manejo outliers

dfcopy1= dfcopy1[dfcopy1["precio"]<5000]
dfcopy1.describe(include="all")

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha
count,4930,4930,4930.000000,4930.000000,4930,4930,4930
unique,6,5,NaN,NaN,3,3,NaN
top,Ana,Mouse,NaN,NaN,Colombia,Transferencia,NaN
freq,858,1051,NaN,NaN,2108,2498,NaN
mean,NaN,NaN,1017.534686,4.931440,NaN,NaN,2024-04-14 21:02:12.900608512
min,NaN,NaN,10.000000,1.000000,NaN,NaN,2024-01-01 00:00:00
25%,NaN,NaN,530.000000,3.000000,NaN,NaN,2024-02-22 11:15:00
50%,NaN,NaN,1023.000000,5.000000,NaN,NaN,2024-04-14 22:30:00
75%,NaN,NaN,1513.000000,7.000000,NaN,NaN,2024-06-05 16:45:00
max,NaN,NaN,1997.000000,9.000000,NaN,NaN,2024-12-04 00:00:00
std,NaN,NaN,570.929918,2.561431,NaN,NaN,NaN

¿Qué problemas encontraste?
se identificaron datos para corregir tipo de información o escritura y datos a corregir porque eran exgerados teniendo en cuenta la media encontrada
¿Cómo los solucionaste?
Tome columna por columna para realizar correcciones como se puede observar en el detalle
¿Eliminaste registros? ¿Por qué?
si, en precio teniendo en cuenta que había un valor que estaba fuera del rango que se podia evidenciar dentro del analisis de la información

Parte 3 — Análisis con Pandas

In [105]:
#crear columna total

dfcopy1['total']= dfcopy1['precio']*dfcopy1['cantidad']
dfcopy1

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha,total
0,Maria,Monitor,1326.0,5.0,Peru,Efectivo,2024-01-01 00:00:00,6630.0
1,Luisa,Laptop,55.0,2.0,Chile,Tarjeta,2024-01-01 01:00:00,110.0
2,Carlos,Monitor,1203.0,9.0,Colombia,Efectivo,2024-01-01 02:00:00,10827.0
3,Luisa,Monitor,1304.0,3.0,Peru,Transferencia,2024-01-01 03:00:00,3912.0
4,Luisa,Monitor,426.0,6.0,Chile,Tarjeta,2024-01-01 04:00:00,2556.0
...,...,...,...,...,...,...,...,...
4995,Juan,Laptop,1582.0,8.0,Chile,Transferencia,2024-07-27 03:00:00,12656.0
4996,Carlos,Mouse,1553.0,2.0,Peru,Tarjeta,2024-07-27 04:00:00,3106.0
4997,Juan,Monitor,1776.0,2.0,Chile,Efectivo,2024-07-27 05:00:00,3552.0
4998,Pedro,Laptop,1366.0,8.0,Chile,Transferencia,2024-07-27 06:00:00,10928.0
4999,Pedro,Mouse,406.0,1.0,Chile,Transferencia,2024-07-27 00:00:00,406.0

In [106]:
#total ventas

dfc1tvtas=dfcopy1["total"].sum()
dfc1tvtas

np.float64(24749303.0)

In [107]:
#promedio de ventas

promvtasdfc1=dfcopy1["total"].mean()
promvtasdfc1

np.float64(5020.142596348885)

In [108]:
#ventas maximas

maxvtasdfc1=dfcopy1["total"].max()
maxvtasdfc1

17955.0

In [109]:
#ventas minimas

minvtasdfc1=dfcopy1["total"].min()
minvtasdfc1

10.0

In [110]:
#Analisis de ventas x pais x >valor
#el país con mayor venta es Colombia

dfcopy1.groupby(["pais"])["total"].sum()

pais
Chile        7114240.0
Colombia    10715371.0
Peru         6919692.0
Name: total, dtype: float64

In [111]:
#productos con mejores ventas
#Los 5 productos con mayor valor vendido

ptos_topdfc1= dfcopy1.groupby(["producto"])["total"].sum().sort_values(ascending=False)
ptos_topdfc1

producto
Mouse      5323479.0
Laptop     5045886.0
Monitor    4872342.0
Celular    4830534.0
Teclado    4677062.0
Name: total, dtype: float64

Parte 4 — Introducción a NumPy

In [112]:
# convertir columnas numericas a un array de Numpy

dataNp = dfcopy1[['precio','cantidad']].to_numpy()
data

array([[1.326e+03, 5.000e+00],
       [5.500e+01, 2.000e+00],
       [1.203e+03, 9.000e+00],
       ...,
       [1.776e+03, 2.000e+00],
       [1.366e+03, 8.000e+00],
       [4.060e+02, 1.000e+00]])

In [113]:
#se utiliza indexacion para separar columnas

precio= dataNp[:,0]
cantidad= dataNp[:,1]
print(dataNp)

[[1.326e+03 5.000e+00]
 [5.500e+01 2.000e+00]
 [1.203e+03 9.000e+00]
 ...
 [1.776e+03 2.000e+00]
 [1.366e+03 8.000e+00]
 [4.060e+02 1.000e+00]]

In [114]:
#ventas totales

Vtas_totales= precio * cantidad
print (Vtas_totales)

[ 6630.   110. 10827. ...  3552. 10928.   406.]

Parte 5 — Análisis con NumPy

In [115]:
#suma total de ventas

Vtas_totales.sum()

np.float64(24749303.0)

In [116]:
#promedio de ventas

Vtas_totales.mean()

np.float64(5020.142596348885)

In [117]:
#venta maxima

Vtas_totales.max()

np.float64(17955.0)

In [118]:
#cantidad de ventas >1000

print("Ventas > 1000: ", len (Vtas_totales[Vtas_totales>1000]))

Ventas > 1000:  4178

¿Qué ventajas observas al usar NumPy?

Es mas practico realizar operaciones, analizar valores de manera más rápida

¿Qué significa “vectorización”?

Es usar la matriz de información para calcular el total de valores que necesitamos

¿Qué hace la expresión data[:, 0]?

Toma la primer columna de la data (indexación) para transformarla en un vector

Parte 6 — Interpretación de resultados
Analiza y responde:
¿Los resultados obtenidos tienen sentido?
teniendo en cuenta que la información recibida se pudo trabajar haciendo limpieza, se obtuvo un resultado estadistico respecto a la data
¿Detectaste valores sospechosos?
Si, por esto se eliminaron datos que ensuciaban la información y estadisticamente desestabilizaba el analisis
¿El promedio representa correctamente los datos?
No, teniendo en cuenta que los datos outliers amplificaron la función estadistica, por lo cual toco filtrar algunos valores
¿Qué decisiones tomarías si esta fuera información real de negocio?
Los resultados del analisis me llevan a recomendar a la compañia estrategicamente en que pais se esta generando mayor demanda, se podria evaluar vtas x producto y asi mismo reforzar inventarios para promover mayores ventas